import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/checkout.module.css'
import Header from '../components/Header'
import Prime from '../components/Prime'
import Product from '../components/Product'
import Subtotal from '../components/Subtotal'

export default function Checkout() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
          <div className={styles.checkout}>
              <div className={styles.checkoutleft}>
                  <div>
                      <h2 className={styles.checkouttitle}>Your Shopping Basket</h2>
                  </div>
              </div>
              <div className={styles.checkoutright}>
                  <h2>The subtotal will be: </h2>
                  <Subtotal></Subtotal>
              </div>

          </div>
      </main>
    </div>
  )
}
